//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.CURRENT_PRODUCT = new HashSet<CURRENT_PRODUCT>();
            this.PRODUCT_DETAIL = new HashSet<PRODUCT_DETAIL>();
        }
    
        public int ID_PRODUCT { get; set; }
        public Nullable<int> ID_TYPE { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string NOTE { get; set; }
    
        public virtual ICollection<CURRENT_PRODUCT> CURRENT_PRODUCT { get; set; }
        public virtual TYPE TYPE { get; set; }
        public virtual ICollection<PRODUCT_DETAIL> PRODUCT_DETAIL { get; set; }
    }
}
