//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_DETAIL
    {
        public int ID_PRODUCTDETAIL { get; set; }
        public Nullable<int> ID_PRODUCT { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string IMAGE { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
