//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE
    {
        public SERVICE()
        {
            this.CURRENT_SERVICE = new HashSet<CURRENT_SERVICE>();
            this.SERVICE_DETAIL = new HashSet<SERVICE_DETAIL>();
        }
    
        public int id { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string NOTE { get; set; }
    
        public virtual ICollection<CURRENT_SERVICE> CURRENT_SERVICE { get; set; }
        public virtual TYPE TYPE { get; set; }
        public virtual ICollection<SERVICE_DETAIL> SERVICE_DETAIL { get; set; }
    }
}
