//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class THEME
    {
        public THEME()
        {
            this.THEMEDETAILs = new HashSet<THEMEDETAIL>();
        }
    
        public int ID_THEME { get; set; }
        public Nullable<int> ID_SITE { get; set; }
        public string BACKGROUND { get; set; }
        public string BACKGROUNDIMAGE { get; set; }
        public string LOGO { get; set; }
        public string SITENAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string NOTE { get; set; }
    
        public virtual SITE SITE { get; set; }
        public virtual ICollection<THEMEDETAIL> THEMEDETAILs { get; set; }
    }
}
