//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_LOGIN
    {
        public string LOGIN_PROVIDER { get; set; }
        public string PROVIDER_KEY { get; set; }
        public int USER_ID { get; set; }
    }
}
