//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    using Infrastructure.Repository;
    
    public partial class USER: BaseEntity
    {
        public USER()
        {
            this.SITEs = new HashSet<SITE>();
            this.USER_ROLE = new HashSet<USER_ROLE>();
            this.USERDETAILs = new HashSet<USERDETAIL>();
        }
    
        public int ID_USER { get; set; }
        public Nullable<short> ID_USERTYPE { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string STATUS { get; set; }
        public string NOTE { get; set; }
    
        public virtual ICollection<SITE> SITEs { get; set; }
        public virtual ICollection<USER_ROLE> USER_ROLE { get; set; }
        public virtual USERTYPE USERTYPE { get; set; }
        public virtual ICollection<USERDETAIL> USERDETAILs { get; set; }
    }
}
