//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_CLAIM
    {
        public int CLAIM_ID { get; set; }
        public int USER_ID { get; set; }
        public string CLAIM_TYPE { get; set; }
        public string CLAIM_VALUE { get; set; }
        public int ID_CLAIM { get; set; }
        public int ID_USER { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
