//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DETAIL
    {
        public int userId { get; set; }
        public short UserTypeId { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual USER_TYPE USER_TYPE { get; set; }
    }
}
