//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERDETAIL
    {
        public int ID_USERDETAIL { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public string FIRSTNAME { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
