//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingMVC4
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int id_student { get; set; }
        public string name { get; set; }
        public string birthday { get; set; }
        public Nullable<double> point { get; set; }
    }
}
