//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFColuc
{
    using System;
    
    public partial class xOrder
    {
        public int orderid { get; set; }
        public string orderstatus { get; set; }
        public string trackingno { get; set; }
        public System.DateTime orderdate { get; set; }
        public string code { get; set; }
        public Nullable<int> size { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> delivery { get; set; }
        public string ordercomment { get; set; }
        public string description { get; set; }
        public string invoiceno { get; set; }
        public string refundtransid { get; set; }
        public Nullable<decimal> refundtotal { get; set; }
        public Nullable<System.DateTime> refunddate { get; set; }
        public string custcomment { get; set; }
    }
}
