//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFColuc
{
    using System;
    
    public partial class xProduct
    {
        public int productid { get; set; }
        public int brandid { get; set; }
        public Nullable<int> langid { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> size { get; set; }
        public string color { get; set; }
        public string brand { get; set; }
    }
}
