//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFNailhub
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.CURRENT_PRODUCT = new HashSet<CURRENT_PRODUCT>();
        }
    
        public int PRODUCT_ID { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string IMAGE { get; set; }
        public decimal COST { get; set; }
        public string DESCRIPTION { get; set; }
        public short ONHAND { get; set; }
        public short ONORDER { get; set; }
        public short QUANTITY { get; set; }
        public string NOTE { get; set; }
        public int ENTERBY { get; set; }
        public System.DateTime ENTERDATE { get; set; }
        public Nullable<int> MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
    
        public virtual ICollection<CURRENT_PRODUCT> CURRENT_PRODUCT { get; set; }
        public virtual TYPE TYPE { get; set; }
    }
}
