//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFNailhub
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE
    {
        public TYPE()
        {
            this.PRODUCTs = new HashSet<PRODUCT>();
            this.SERVICEs = new HashSet<SERVICE>();
        }
    
        public int TYPE_ID { get; set; }
        public string NAME { get; set; }
        public string MADE_BY { get; set; }
        public string MADE_IN { get; set; }
        public string MADE_OF { get; set; }
        public string DESCRIPTION { get; set; }
        public string NOTE { get; set; }
        public int ENTERBY { get; set; }
        public System.DateTime ENTERDATE { get; set; }
        public Nullable<int> MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
    
        public virtual ICollection<PRODUCT> PRODUCTs { get; set; }
        public virtual ICollection<SERVICE> SERVICEs { get; set; }
    }
}
