//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFNailhubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int EMPLOYEE_ID { get; set; }
        public Nullable<short> TITLE_ID { get; set; }
        public int SITE_ID { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int ENTERBY { get; set; }
        public System.DateTime ENTERDATE { get; set; }
        public Nullable<int> MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string COMMENT { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual SITE SITE { get; set; }
        public virtual Title Title { get; set; }
    }
}
