//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFNailhubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITE
    {
        public SITE()
        {
            this.CURRENT_PRODUCT = new HashSet<CURRENT_PRODUCT>();
            this.CURRENT_SERVICE = new HashSet<CURRENT_SERVICE>();
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
            this.THEMEs = new HashSet<THEME>();
        }
    
        public int SITE_ID { get; set; }
        public Nullable<short> SITE_TYPE_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string SUBDOMAIN { get; set; }
        public string HOST { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string NOTE { get; set; }
        public int ENTERBY { get; set; }
        public System.DateTime ENTERDATE { get; set; }
        public Nullable<int> MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string COMMENT { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<CURRENT_PRODUCT> CURRENT_PRODUCT { get; set; }
        public virtual ICollection<CURRENT_SERVICE> CURRENT_SERVICE { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual SITE_TYPE SITE_TYPE { get; set; }
        public virtual ICollection<THEME> THEMEs { get; set; }
    }
}
