//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFNailhubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class THEME
    {
        public THEME()
        {
            this.THEME_DETAIL = new HashSet<THEME_DETAIL>();
        }
    
        public int THEME_ID { get; set; }
        public Nullable<int> SITE_ID { get; set; }
        public string CSS_FILE { get; set; }
        public string LOGO { get; set; }
        public string SITENAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string NOTE { get; set; }
        public int ENTERBY { get; set; }
        public System.DateTime ENTERDATE { get; set; }
        public Nullable<int> MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string COMMENT { get; set; }
    
        public virtual SITE SITE { get; set; }
        public virtual ICollection<THEME_DETAIL> THEME_DETAIL { get; set; }
    }
}
