//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class THEME
    {
        public THEME()
        {
            this.THEME_DETAIL = new HashSet<THEME_DETAIL>();
        }
    
        public int id { get; set; }
        public Nullable<int> SITE_ID { get; set; }
        public string BACKGROUND { get; set; }
        public string BACKGROUNDIMAGE { get; set; }
        public string LOGO { get; set; }
        public string SITENAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string NOTE { get; set; }
    
        public virtual SITE SITE { get; set; }
        public virtual ICollection<THEME_DETAIL> THEME_DETAIL { get; set; }
    }
}
