USE [master]
GO

/****** Object:  Database [CoLuc]    Script Date: 4/4/2015 2:40:40 PM ******/
CREATE DATABASE [CoLuc]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CoLuc', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXP2014\MSSQL\DATA\CoLuc.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CoLuc_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXP2014\MSSQL\DATA\CoLuc_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CoLuc] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CoLuc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CoLuc] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CoLuc] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CoLuc] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CoLuc] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CoLuc] SET ARITHABORT OFF 
GO

ALTER DATABASE [CoLuc] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CoLuc] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CoLuc] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CoLuc] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CoLuc] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CoLuc] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CoLuc] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CoLuc] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CoLuc] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CoLuc] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CoLuc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CoLuc] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CoLuc] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CoLuc] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CoLuc] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CoLuc] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [CoLuc] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CoLuc] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CoLuc] SET  MULTI_USER 
GO

ALTER DATABASE [CoLuc] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CoLuc] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CoLuc] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CoLuc] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CoLuc] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CoLuc] SET  READ_WRITE 
GO

